services:
  mysql:
    image: mysql:8.0
    container_name: employee-task-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee_task_tracker
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backend:
    image: 703139106911.dkr.ecr.ap-south-1.amazonaws.com/tasks-backend:latest
    container_name: employee-task-backend
    env_file: ./backend/.env.production
    ports:
      - "5001:5001"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: 703139106911.dkr.ecr.ap-south-1.amazonaws.com/tasks-frontend:latest
    container_name: employee-task-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
